name: 'Feature request'
description: 'If you have a way to improve this project, please specify it here.'
labels: ['enhancement']
body:
    - type: textarea
      id: problem
      attributes:
          label: 'Related Problem'
          description: 'Is your feature related to a problem? If so, please describe the problem.'
      validations:
          required: false
    - type: textarea
      id: solution
      attributes:
          label: 'Requested Feature'
          description: 'Describe the feature you want to add. Be as detailed as possible.'
      validations:
          required: true
